# Generated by Django 5.1.4 on 2024-12-31 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "post_transaction_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("transaction_details", models.CharField(max_length=100)),
                ("transaction_type", models.CharField(max_length=10)),
                ("transaction_method", models.CharField(blank=True, max_length=10)),
                ("transaction_date", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
