# Generated by Django 5.1.4 on 2025-01-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_history", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="transaction_id",
            new_name="id",
        ),
    ]
