# Generated by Django 5.1.4 on 2025-01-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction_history",
            "0003_alter_transactionhistory_transaction_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="post_transaction_balance",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18),
        ),
    ]
