# Generated by Django 5.1.4 on 2025-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction_history",
            "0004_alter_transactionhistory_post_transaction_balance",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="post_transaction_balance",
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
