# Generated by Django 5.1.4 on 2025-01-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_balance"),
        (
            "transaction_history",
            "0005_alter_transactionhistory_post_transaction_balance",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="id",
            new_name="transaction_id",
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.account",
            ),
        ),
    ]
