# Generated by Django 5.1.4 on 2025-01-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_type_alter_account_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_code',
            field=models.CharField(choices=[('000', '서울은행'), ('001', '국민은행'), ('002', '우리은행'), ('003', '하나은행'), ('004', '농협은행'), ('005', '신한은행'), ('007', '외환은행'), ('008', '씨티은행'), ('011', '한국씨티은행'), ('012', '한국산업은행'), ('020', '경남은행'), ('023', 'SC제일은행'), ('027', '기업은행'), ('031', '부산은행'), ('032', '대구은행'), ('034', '광주은행'), ('035', '제주은행'), ('037', '하나카드'), ('039', '카카오뱅크'), ('045', '하나금융투자'), ('048', '대신증권'), ('050', '한국투자증권'), ('051', '삼성증권'), ('052', 'NH투자증권'), ('054', 'HSBC은행'), ('055', '농협중앙회')], max_length=10, verbose_name='Bank Code'),
        ),
    ]
