# Generated by Django 4.2.17 on 2025-01-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Analysis ID')),
                ('analysis_target', models.CharField(max_length=10, verbose_name='Bank Code')),
                ('analysis_period', models.CharField(max_length=20, verbose_name='Account Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/analysis/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='users.user')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='analysis_an_user_id_503cc5_idx')],
            },
        ),
    ]
