name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Django CI Pipeline
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        options: >-
          --health-cmd="pg_isready -h 127.0.0.1 -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:${{ secrets.PG_PASSWORD }}@127.0.0.1:5432/${{ secrets.PG_NAME }}
      DJANGO_SETTINGS_MODULE: myproject.settings
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_ENV

      - name: Install Packages & Libraries
        run: |
          poetry install --with ci

      - name: Run isort (Import sorting)
        run: |
          poetry run isort . --check --diff

      - name: Run black (Code formatting)
        run: |
          poetry run black . --check

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Run Django Migrations
        run: |
          poetry run python manage.py migrate

      - name: Run Django Tests
        run: |
          poetry run python manage.py test
